{
 "title": "DiscordRoleManager",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DB Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  value AS metric\nFROM metadata\nGROUP BY value"
    }
   ]
  },
  {
   "title": "Active Donators",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(username) as metric FROM temporary_roles;"
    }
   ]
  },
  {
   "title": "Donators",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT username as Donator, FROM_UNIXTIME(endDate) as expireDate FROM temporary_roles ORDER BY expireDate asc;"
    }
   ]
  }
 ]
}